export const sampletestdata = [
  [
    {
    passage: (
      <>
        Arturo A. Schomburg was dedicated to preserving books, art, and other materials from peoples of African descent around the world. To get these items, Schomburg <u>depended on</u> friends and colleagues, whom he asked to bring back rare and valuable objects from their international travels. Now, Schomburg’s collection is a valuable resource for scholars of Black history and culture. This is a normal sentence. <u>This part is underlined.</u>
      </>
    ),
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choice1: 'admired',
    choice2: 'disagreed with',
    choice3: 'warned',
    choice4: 'depended on',
    answer: 'D',
    },
    {
    passage: 'In 1877, 85% of California’s railways were already controlled by the Southern Pacific Railroad. The company further solidified its ______ in rail access to the state’s Pacific coast when it completed the Sunset Route in 1883: running from Louisiana to Southern California, the route established the first transcontinental rail line across the southern United States.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choice1: 'dominance',
    choice2: 'creativity',
    choice3: 'insignificance',
    choice4: 'neutrality',
    answer: 'A',
    },
    {
    passage: `The following text is adapted from Sui Sin Far’s 1912 short story “Mrs. Spring Fragrance.” Mr. and Mrs. Spring Fragrance immigrated to the United States from China.

Mrs. Spring Fragrance was unaware that Mr. Spring Fragrance, tired with the day’s business, had thrown himself down on the bamboo settee on the veranda, and that although his eyes were engaged in scanning the pages of the Chinese World, his ears could not help r͟e͟c͟e͟i͟v͟i͟n͟g the words which were borne to him through the open window.`,
    question: 'As used in the text, what does the word “receiving” most nearly mean?',
    choice1: 'Denying',
    choice2: 'Entering',
    choice3: 'Carrying',
    choice4: 'Hearing',
    answer: 'D',
    },
    {
    passage: 'Some people have speculated that two helmets with attached horns discovered in Denmark in 1942 belonged to Vikings, but scholars have long been skeptical. Archaeologist Helle Vandkilde and colleagues recently provided radiocarbon dates for the helmets, and their findings ______ scholars’ skepticism: the helmets date to the Nordic Bronze Age, centuries before the Vikings existed.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choice1: 'anticipate',
    choice2: 'inspect',
    choice3: 'reveal',
    choice4: 'justify',
    answer: 'D',
    },
    {
    passage: `The following text is adapted from Louisa May Alcott’s 1869 novel An Old-Fashioned Girl. Polly, a teenager, is visiting her friend Fanny.

    Fanny’s friends did not interest Polly much; she was rather afraid of them [because] they seemed so much older and wiser than herself, even those younger in years. They talked about things of which she knew nothing and when Fanny tried to explain, she didn’t find them interesting; indeed, some of them rather shocked and puzzled her.`,
    question: 'Which choice best states the main purpose of the text?',
    choice1: 'To portray Polly’s reaction to Fanny’s friends',
    choice2: 'To identify the topics Polly talks about with Fanny’s friends',
    choice3: 'To explain how Fanny met some of her friends',
    choice4: 'To illustrate how Fanny’s friends feel about Polly',
    answer: 'A',
    },
    {
    passage: 'San Francisco is known for the colorful murals painted on many of its buildings. The densest collection of murals is found on Balmy Alley in the Mission District neighborhood. In the 1970s, Latina artists painted vivid scenes of community life on walls along this block. As the original murals have faded, later generations of artists have painted new ones over them. As a result, Balmy Alley has become a living showcase of San Francisco’s artistic spirit, with its murals reflecting changes in the cultural life of the city.',
    question: 'Which choice best states the main purpose of the text?',
    choice1: 'To compare the Balmy Alley murals to other murals in San Francisco',
    choice2: 'To offer an overview of the history and importance of the Balmy Alley murals',
    choice3: 'To urge people to protect the murals of San Francisco from decay',
    choice4: 'To describe the rise of mural painting in San Francisco beginning in the 1970s',
    answer: 'B',
    },
    {
    passage: 'In 1801, a Blackfoot chief named Ac Ko Mok Ki drew a finely detailed map of the Upper Missouri region. T͟h͟i͟s͟ w͟o͟r͟k͟ d͟e͟m͟o͟n͟s͟t͟r͟a͟t͟e͟s͟ a͟ v͟a͟s͟t͟ a͟m͟o͟u͟n͟t͟ o͟f͟ t͟o͟p͟o͟g͟r͟a͟p͟h͟i͟c͟ k͟n͟o͟w͟l͟e͟d͟g͟e͟, a͟s͟ t͟h͟e͟ m͟a͟p͟ f͟e͟a͟t͟u͟r͟e͟s͟ s͟p͟e͟c͟i͟f͟i͟c͟ n͟a͟m͟e͟s͟ o͟f͟ m͟o͟u͟n͟t͟a͟i͟n͟s͟ a͟n͟d͟ r͟i͟v͟e͟r͟s͟, a͟s͟ w͟e͟l͟l͟ a͟s͟ t͟h͟e͟ f͟i͟r͟s͟t͟-k͟n͟o͟w͟n͟ s͟k͟e͟t͟c͟h͟ o͟f͟ t͟h͟e͟ d͟r͟a͟i͟n͟a͟g͟e͟ n͟e͟t͟w͟o͟r͟k͟ o͟f͟ t͟h͟e͟ M͟i͟s͟s͟o͟u͟r͟i͟ R͟i͟v͟e͟r͟. The map is especially notable because Ac Ko Mok Ki also included details about the numerous tribes that lived in the area.',
    question: 'Which choice best describes the function of the underlined sentence in the text as a whole?',
    choice1: 'It emphasizes Ac Ko Mok Ki’s desire to represent other tribes on the map.',
    choice2: 'It explains how Ac Ko Mok Ki developed an interest in mapmaking.',
    choice3: 'It identifies some reasons why the map is impressive.',
    choice4: 'It details how the map was used for hunting and trading purposes.',
    answer: 'C',
    },
    {
    passage: 'Y͟a͟w͟n͟ c͟o͟n͟t͟a͟g͟i͟o͟n͟ o͟c͟c͟u͟r͟s͟ w͟h͟e͟n͟ o͟n͟e͟ i͟n͟d͟i͟v͟i͟d͟u͟a͟l͟ y͟a͟w͟n͟s͟ i͟n͟ r͟e͟s͟p͟o͟n͟s͟e͟ t͟o͟ a͟n͟o͟t͟h͟e͟r͟’s͟ y͟a͟w͟n͟. Studies of this behavior in primates have focused on populations in captivity, but biologist Elisabetta Palagi and her colleagues have shown that it can occur in wild primate populations as well. In their study, which focused on a wild population of gelada monkeys (Theropithecus gelada) in Ethiopia, the researchers further reported that yawn contagion most commonly occurred in males and across different social groups instead of within a single social group.',
    question: 'Which choice best describes the function of the first sentence in the text as a whole?',
    choice1: 'It defines a phenomenon that is discussed in the text.',
    choice2: 'It introduces a problem that is examined in the text.',
    choice3: 'It makes a claim that is challenged in the text.',
    choice4: 'It presents a hypothesis that is evaluated in the text.',
    answer: 'A',
    },
    {
    passage: `The following text is adapted from Paul Laurence Dunbar’s 1902 novel The Sport of the Gods. Joe and some of his family members have recently moved to New York City.

    [Joe] was wild with enthusiasm and with a desire to be a part of all that the metropolis meant. In the evening he saw the young fellows passing by dressed in their spruce clothes, and he wondered with a sort of envy where they could be going. Back home there had been no place much worth going to, except church and one or two people’s houses.`,
    question: 'Which choice best states the main purpose of the text?',
    choice1: 'It illustrates a character’s reaction to a new environment.',
    choice2: 'It explains why a character has traveled to a city.',
    choice3: 'It compares a character’s thoughts about an event at two different times of day.',
    choice4: 'It presents a character feeling regret over leaving home.',
    answer: 'A',
    },
    {
    passage: `The following text is adapted from Johanna Spyri’s 1881 novel Heidi (translated by Elisabeth Stork in 1915). Eight-year-old Heidi and her friend’s grandmother are looking at some illustrated books.

    Heidi had come and was looking with wondering eyes at the splendid pictures in the large books, that Grandmama was showing her. Suddenly she screamed aloud, for there on the picture she saw a peaceful flock grazing on a green pasture. In the middle a shepherd was standing, leaning on his crook. The setting sun was shedding a golden light over everything. With glowing eyes Heidi devoured the scene.`,
    question: 'Which choice best states the main idea of the text?',
    choice1: 'Heidi is upset until she sees a serene image of a pasture in one of Grandmama’s books.',
    choice2: 'Heidi is delighted and fascinated by an image she sees in one of Grandmama’s books.',
    choice3: 'Heidi is initially frightened by an image in one of Grandmama’s books but quickly comes to appreciate its beauty.',
    choice4: 'Heidi is inspecting an image in one of Grandmama’s books because she has never seen a shepherd with his sheep before.',
    answer: 'B',
    },
    {
    passage: 'The painter María Izquierdo played an important role in the development of twentieth-century Mexican art, but her work has never been well-known in the United States except among art historians. One reason for Izquierdo’s relative obscurity is the enormous popularity of some of her peers. In particular, the painters Frida Kahlo and Diego Rivera have so captivated the interest of US audiences that Izquierdo and other Mexican artists from the period often get overlooked, despite the high quality of their work.',
    question: 'Which choice best states the main idea of the text?',
    choice1: 'Izquierdo’s work is not as well-known in the United States as it should be because Kahlo and Rivera draw so much of the public’s attention.',
    choice2: 'During Izquierdo’s lifetime, her paintings were displayed in galleries in the United States much more frequently than paintings by Kahlo and Rivera were.',
    choice3: 'Izquierdo painted some of the same subjects that Kahlo and Rivera painted but used different techniques than they used.',
    choice4: 'Few of Izquierdo’s works are in galleries today because she produced only a small number of paintings.',
    answer: 'A',
    },
    {
    passage: 'The recovery of a 1,000-year-old Chinese shipwreck in the Java Sea near present-day Indonesia has yielded a treasure trove of artifacts, including thousands of small ceramic bowls. Using a portable X-ray fluorescence analyzer tool, Lisa Niziolek and her team were able to detect the chemical composition of these bowls without damaging them. By comparing the chemical signatures of the bowls with those of the materials still at old Chinese kiln sites, Niziolek and her team can pinpoint which Chinese kilns likely produced the ceramic bowls',
    question: 'Which choice best states the main idea of the text?',
    choice1: 'Because of a new technology, researchers can locate and recover more shipwrecks than they could in the past.',
    choice2: 'Researchers have been able to identify the location of a number of Chinese kilns in operation 1,000 years ago.',
    choice3: 'With the help of a special tool, researchers have determined the likely origin of bowls recovered from a shipwreck.',
    choice4: 'Before the invention of portable X-ray fluorescence, researchers needed to take a small piece out of an artifact to analyze its components.',
    answer: 'C',
    },
    {
    passage: 'Sandra Cisneros’s 1984 novella The House on Mango Street made a lasting impact on US literature. Its depiction of Mexican American culture inspired later authors to examine their own heritage within their fictional works. Also influential was the book’s portrayal of the main character, Esperanza, during a pivotal year of her youth. T͟h͟i͟s͟ i͟n͟s͟i͟g͟h͟t͟f͟u͟l͟ d͟e͟p͟i͟c͟t͟i͟o͟n͟ o͟f͟ a͟ p͟r͟e͟t͟e͟e͟n͟ g͟i͟r͟l͟ e͟n͟c͟o͟u͟r͟a͟g͟e͟d͟ a͟u͟t͟h͟o͟r͟s͟ w͟h͟o͟, l͟i͟k͟e͟ C͟i͟s͟n͟e͟r͟o͟s͟ h͟e͟r͟s͟e͟l͟f͟, a͟r͟e͟ L͟a͟t͟i͟n͟a͟ t͟o͟ u͟s͟e͟ f͟i͟c͟t͟i͟o͟n͟a͟l͟ w͟o͟r͟k͟s͟ t͟o͟ e͟x͟a͟m͟i͟n͟e͟ e͟x͟p͟e͟r͟i͟e͟n͟c͟e͟s͟ f͟r͟o͟m͟ t͟h͟e͟i͟r͟ o͟w͟n͟ y͟o͟u͟t͟h͟.',
    question: 'Which statement, if true, would most strongly support the claim in the underlined sentence?',
    choice1: 'In interviews, a number of Latina authors say that The House on Mango Street inspired them to write about their own adolescence in their novels.',
    choice2: 'In published writings, several prominent authors who are not Latina say that reading The House on Mango Street influenced their approach to writing fiction.',
    choice3: 'The House on Mango Street has sold over six million copies and is one of the most commonly read books among high school and university students in the US.',
    choice4: 'Since 1984, new novels about young Latina characters by Latina authors have often been compared to The House on Mango Street.',
    answer: 'A',
    },
    {
      img: 'psat8-9r1-14.png',
    passage: 'A student is researching monthly hours of sunshine in different cities in Alaska. When comparing trends in Anchorage and Fairbanks, the student concludes that the two cities show a similar pattern in the monthly hours of sunshine from April to September.',
    question: 'Which choice best describes data from the graph that support the student’s conclusion?',
    choice1: 'The monthly hours of sunshine in both Anchorage and Fairbanks hold steady in June and July before beginning to decline in August.',
    choice2: 'The monthly hours of sunshine in both Anchorage and Fairbanks increase from April to June and then decrease from June to September.',
    choice3: 'Anchorage and Fairbanks both have less than 200 monthly hours of sunshine from April to September.',
    choice4: 'Anchorage and Fairbanks both have more than 300 monthly hours of sunshine from April to June and less than 200 hours from July to September.',
    answer: 'B',
    },
    {
    img: 'psat8-9r1-15.png',
    passage: 'Swahili is estimated to be the first language of up to 15 million people worldwide. It’s also an officially recognized language in Tanzania, Kenya, and the Democratic Republic of the Congo, which means these countries use Swahili in government documents and proceedings. B͟u͟t͟ e͟v͟e͟n͟ i͟n͟ c͟o͟u͟n͟t͟r͟i͟e͟s͟ w͟h͟e͟r͟e͟ a͟l͟m͟o͟s͟t͟ e͟v͟e͟r͟y͟o͟n͟e͟ s͟p͟e͟a͟k͟s͟ S͟w͟a͟h͟i͟l͟i͟, f͟o͟r͟ m͟a͟n͟y͟ i͟t͟ i͟s͟n͟\'t͟ t͟h͟e͟i͟r͟ f͟i͟r͟s͟t͟ l͟a͟n͟g͟u͟a͟g͟e͟ b͟u͟t͟ i͟s͟ i͟n͟s͟t͟e͟a͟d͟ t͟h͟e͟i͟r͟ s͟e͟c͟o͟n͟d͟, t͟h͟i͟r͟d͟, o͟r͟ e͟v͟e͟n͟ f͟o͟u͟r͟t͟h͟ l͟a͟n͟g͟u͟a͟g͟e͟.',
    question: 'Which choice most effectively uses data from the table to support the underlined claim?',
    choice1: 'Tanzania has approximately 61 million Swahili speakers, which is much more than the estimated total number of people worldwide for whom Swahili is their first language.',
    choice2: 'Tanzania is estimated to have at most 15 million Swahili speakers, while the country’s total population is approximately 61 million people.',
    choice3: 'Approximately 100 percent of the people who speak Swahili as their first language live in Kenya, which has a total population of approximately 55 million people.',
    choice4: 'Approximately 100 percent of Kenya’s population speaks Swahili, while only about 25 percent of the Democratic Republic of the Congo’s population speaks Swahili.',
    answer: 'A',
    },
    {
    passage: 'To create the poems in her 2017 collection One Last Word, poet Nikki Grimes used a writing method called the golden shovel. This method often involves choosing a line from an existing poem and then using each word from that line as the last word of each line in a new poem. Grimes wanted the poems in One Last Word to honor important Black poets of the past, so she chose lines by poets such as Langston Hughes and Georgia Douglas Johnson. Writing in this way can be challenging and might seem as though it would produce awkward poems. However, reviewers praised One Last Word as a beautiful and powerful tribute to the poets who inspired it. This reaction suggests that ______',
    question: 'Which choice most logically completes the text?',
    choice1: 'most reviewers didn’t understand Grimes’s goal for One Last Word.',
    choice2: 'Grimes successfully used the golden shovel method to achieve her goal for One Last Word.',
    choice3: 'Langston Hughes and Georgia Douglas Johnson are two of Grimes’s favorite poets.',
    choice4: 'Grimes inspired many other writers to create poems using the golden shovel method.',
    answer: 'B',
    },
    {
    passage: 'Why are Rome’s famous concrete structures, such as the Colosseum, still standing after 2,000-plus years, when modern concrete may not even last for fifty? Scientists ______ that the secret to Roman concrete’s durability was its unique blend of ingredients, which included volcanic ash and seawater.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choice1: 'explain',
    choice2: 'having explained',
    choice3: 'explaining',
    choice4: 'to explain',
    answer: 'A',
    },
    {
    passage: 'In the 2011 documentary The Barber of Birmingham, civil rights activist James Armstrong recounts how his barbershop in Birmingham, Alabama, ______ as a political hub for members of the Black community during the 1950s.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choice1: 'serving',
    choice2: 'having served',
    choice3: 'served',
    choice4: 'to serve',
    answer: 'C',
    },
    {
    passage: 'Led by Syrian American astronomer Shadia Habbal, the Solar Wind Sherpas are an intrepid team of scientists who travel the globe to study solar winds, the streams of particles emanating from the Sun that are only visible from certain locations during a total solar eclipse. When such an eclipse is imminent, the Sherpas pack up their telescopes and ______ ready.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choice1: 'get',
    choice2: 'had gotten',
    choice3: 'got',
    choice4: 'were getting',
    answer: 'A',
    },
    {
    passage: 'In 2017, artists Isabel and Ruben Toledo redesigned the costumes and sets for The Miami City Ballet’s production of The ______ to reviewers, the Toledos’ designs helped infuse the production with elements of Miami’s Latin American culture.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choice1: 'Nutcracker according,',
    choice2: 'Nutcracker, according',
    choice3: 'Nutcracker according',
    choice4: 'Nutcracker. According',
    answer: 'D',
    },
    {
    passage: 'Po’Pay was a Tewa leader from Ohkay Owingeh, a pueblo located about twenty-five miles north of present-day Santa Fe, New Mexico. He was instrumental in organizing the Pueblo Revolt of ______ as a result of his leadership, the Spanish colonizers were expelled from the region for a time.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choice1: '1680',
    choice2: '1680 and',
    choice3: '1680,',
    choice4: '1680, and',
    answer: 'D',
    },
    {
    passage: 'In Gothic architecture, flying buttresses are large arches that help support a building’s exterior walls. Before the Gothic era, cathedrals’ heavy ceilings had to be supported by thick, short walls, but the invention of flying buttresses eliminated this need. ______ Gothic cathedrals could be built with thinner, higher walls.',
    question: 'Which choice completes the text with the most logical transition?',
    choice1: 'Similarly,',
    choice2: 'For instance,',
    choice3: 'Nevertheless,',
    choice4: 'As a result,',
    answer: 'D',
    },
    {
    passage: 'In June, female loggerhead sea turtles will swim back to the sandy beaches where they were born to lay eggs of their own. First, the turtle will dig her nest in the sand. ______ she will lay up to 100 eggs in the nest. Finally, she will cover it all with sand, before returning to the ocean.',
    question: 'Which choice completes the text with the most logical transition?',
    choice1: 'By contrast,',
    choice2: 'Similarly,',
    choice3: 'Next,',
    choice4: 'For example,',
    answer: 'C',
    },
    {
    passage: 'In 1873, Spanish scientist Santiago Ramón y Cajal observed that brain fibers have distinct boundaries with clear end points, a finding that went against earlier assumptions about the brain. ______ scientists had assumed that the brain was a continuous web of fused fibers, not a vast network of distinct, individual cells.',
    question: 'Which choice completes the text with the most logical transition?',
    choice1: 'However,',
    choice2: 'Previously,',
    choice3: 'As a result,',
    choice4: 'Likewise,',
    answer: 'B',
    },
    {
    passage: `While researching a topic, a student has taken the following notes: 

    •The Sasanian Empire lasted about 400 years (AD 224 to AD 651).
    •The Sasanians controlled an area spanning 1.4 million square miles.
    •This area included present-day Iran and Iraq.
    •The empire’s capital was the ancient city of Ctesiphon.
    •Ctesiphon was located near present-day Baghdad, Iraq.`,
    question: 'The student wants to specify the location of Ctesiphon. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choice1: 'The Sasanian Empire began in AD 224 and ended in AD 651.',
    choice2: 'The capital of the Sasanian Empire, which spanned 1.4 million square miles, was Ctesiphon.',
    choice3: 'The Sasanians controlled an area of 1.4 million square miles, including present-day Iran and Iraq.',
    choice4: 'Ctesiphon, the capital of the Sasanian Empire, was located near present-day Baghdad, Iraq.',
    answer: 'D',
    },
    {
    passage: `While researching a topic, a student has taken the following notes:

    •In the art world, the term biennial traditionally refers to an art exhibition that takes place every two years in a single location.
    •Such biennials are held in New York, Berlin, and Venice.
    •In 2006, artists Ed Gomez and Luis Hernandez founded the unconventional MexiCali Biennial.
    •The MexiCali Biennial hosts exhibitions in different venues on both sides of the US-Mexico border.
    •The MexiCali Biennial has taken place on an uneven schedule, with exhibitions in 2006, 2009–10, 2013, and 2018–20.`,
    question: 'The student wants to emphasize a difference between the MexiCali Biennial and traditional biennials. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choice1: 'In 2006, artists Ed Gomez and Luis Hernandez founded the MexiCali Biennial, which has taken place in 2006, 2009–10, 2013, and 2018–20.',
    choice2: 'Unlike traditional biennials, the MexiCali Biennial hosts exhibitions in different venues on an uneven schedule.',
    choice3: 'The term biennial traditionally refers to an art exhibition that takes place every two years in a single location, not to exhibitions hosted at a variety of times and venues.',
    choice4: 'Biennial exhibitions have been held in New York, Berlin, and Venice but also on both sides of the US-Mexico border.',
    answer: 'B',
    },
    {
    passage: `While researching a topic, a student has taken the following notes:

    •Allan Houser was a Chiricahua Warm Springs Apache sculptor, illustrator, and painter.
    •Many of his sculptures featured Native American figures.
    •He depicted this subject matter using abstract, modernist forms, developing a distinctive style that influenced many other artists.
    •His well-known sculpture Sacred Rain Arrow was pictured on the State of Oklahoma license plate.`,
    question: 'The student wants to describe the distinctive style of Houser’s sculptures. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choice1: 'A sculptor, illustrator, and painter, Houser developed a distinctive style for portraying Native American figures.',
    choice2: 'Houser’s sculptures employ abstract, modernist forms to depict Native American figures.',
    choice3: 'Many other artists have been influenced by the style of Houser’s sculptures.',
    choice4: 'The sculpture Sacred Rain Arrow is a well-known example of Houser’s style.',
    answer: 'B',
    }],
    [
      {
      passage: '2rturo 2. Schomburg was dedicated to preserving books, art, and other materials from peoples of African descent around the world. To get these items, Schomburg ______ friends and colleagues, whom he asked to bring back rare and valuable objects from their international travels. Now, Schomburg’s collection is a valuable resource for scholars of Black history and culture.',
      question: 'Which choice completes the text with the most logical and precise word or phrase?',
      choice1: 'admired',
      choice2: 'disagreed with',
      choice3: 'warned',
      choice4: 'depended on',
      answer: 'D',
      },
      {
      passage: 'In 1877, 85% of California’s railways were already controlled by the Southern Pacific Railroad. The company further solidified its ______ in rail access to the state’s Pacific coast when it completed the Sunset Route in 1883: running from Louisiana to Southern California, the route established the first transcontinental rail line across the southern United States.',
      question: 'Which choice completes the text with the most logical and precise word or phrase?',
      choice1: 'dominance',
      choice2: 'creativity',
      choice3: 'insignificance',
      choice4: 'neutrality',
      answer: 'A',
      },
      {
      passage: `The following text is adapted from Sui Sin Far’s 1912 short story “Mrs. Spring Fragrance.” Mr. and Mrs. Spring Fragrance immigrated to the United States from China.
    
    Mrs. Spring Fragrance was unaware that Mr. Spring Fragrance, tired with the day’s business, had thrown himself down on the bamboo settee on the veranda, and that although his eyes were engaged in scanning the pages of the Chinese World, his ears could not help r͟e͟c͟e͟i͟v͟i͟n͟g the words which were borne to him through the open window.`,
      question: 'As used in the text, what does the word “receiving” most nearly mean?',
      choice1: 'Denying',
      choice2: 'Entering',
      choice3: 'Carrying',
      choice4: 'Hearing',
      answer: 'D',
      },
      {
      passage: 'Some people have speculated that two helmets with attached horns discovered in Denmark in 1942 belonged to Vikings, but scholars have long been skeptical. Archaeologist Helle Vandkilde and colleagues recently provided radiocarbon dates for the helmets, and their findings ______ scholars’ skepticism: the helmets date to the Nordic Bronze Age, centuries before the Vikings existed.',
      question: 'Which choice completes the text with the most logical and precise word or phrase?',
      choice1: 'anticipate',
      choice2: 'inspect',
      choice3: 'reveal',
      choice4: 'justify',
      answer: 'D',
      },
      {
      passage: `The following text is adapted from Louisa May Alcott’s 1869 novel An Old-Fashioned Girl. Polly, a teenager, is visiting her friend Fanny.
    
      Fanny’s friends did not interest Polly much; she was rather afraid of them [because] they seemed so much older and wiser than herself, even those younger in years. They talked about things of which she knew nothing and when Fanny tried to explain, she didn’t find them interesting; indeed, some of them rather shocked and puzzled her.`,
      question: 'Which choice best states the main purpose of the text?',
      choice1: 'To portray Polly’s reaction to Fanny’s friends',
      choice2: 'To identify the topics Polly talks about with Fanny’s friends',
      choice3: 'To explain how Fanny met some of her friends',
      choice4: 'To illustrate how Fanny’s friends feel about Polly',
      answer: 'A',
      },
      {
      passage: 'San Francisco is known for the colorful murals painted on many of its buildings. The densest collection of murals is found on Balmy Alley in the Mission District neighborhood. In the 1970s, Latina artists painted vivid scenes of community life on walls along this block. As the original murals have faded, later generations of artists have painted new ones over them. As a result, Balmy Alley has become a living showcase of San Francisco’s artistic spirit, with its murals reflecting changes in the cultural life of the city.',
      question: 'Which choice best states the main purpose of the text?',
      choice1: 'To compare the Balmy Alley murals to other murals in San Francisco',
      choice2: 'To offer an overview of the history and importance of the Balmy Alley murals',
      choice3: 'To urge people to protect the murals of San Francisco from decay',
      choice4: 'To describe the rise of mural painting in San Francisco beginning in the 1970s',
      answer: 'B',
      },
      {
      passage: 'In 1801, a Blackfoot chief named Ac Ko Mok Ki drew a finely detailed map of the Upper Missouri region. T͟h͟i͟s͟ w͟o͟r͟k͟ d͟e͟m͟o͟n͟s͟t͟r͟a͟t͟e͟s͟ a͟ v͟a͟s͟t͟ a͟m͟o͟u͟n͟t͟ o͟f͟ t͟o͟p͟o͟g͟r͟a͟p͟h͟i͟c͟ k͟n͟o͟w͟l͟e͟d͟g͟e͟, a͟s͟ t͟h͟e͟ m͟a͟p͟ f͟e͟a͟t͟u͟r͟e͟s͟ s͟p͟e͟c͟i͟f͟i͟c͟ n͟a͟m͟e͟s͟ o͟f͟ m͟o͟u͟n͟t͟a͟i͟n͟s͟ a͟n͟d͟ r͟i͟v͟e͟r͟s͟, a͟s͟ w͟e͟l͟l͟ a͟s͟ t͟h͟e͟ f͟i͟r͟s͟t͟-k͟n͟o͟w͟n͟ s͟k͟e͟t͟c͟h͟ o͟f͟ t͟h͟e͟ d͟r͟a͟i͟n͟a͟g͟e͟ n͟e͟t͟w͟o͟r͟k͟ o͟f͟ t͟h͟e͟ M͟i͟s͟s͟o͟u͟r͟i͟ R͟i͟v͟e͟r͟. The map is especially notable because Ac Ko Mok Ki also included details about the numerous tribes that lived in the area.',
      question: 'Which choice best describes the function of the underlined sentence in the text as a whole?',
      choice1: 'It emphasizes Ac Ko Mok Ki’s desire to represent other tribes on the map.',
      choice2: 'It explains how Ac Ko Mok Ki developed an interest in mapmaking.',
      choice3: 'It identifies some reasons why the map is impressive.',
      choice4: 'It details how the map was used for hunting and trading purposes.',
      answer: 'C',
      },
      {
      passage: 'Y͟a͟w͟n͟ c͟o͟n͟t͟a͟g͟i͟o͟n͟ o͟c͟c͟u͟r͟s͟ w͟h͟e͟n͟ o͟n͟e͟ i͟n͟d͟i͟v͟i͟d͟u͟a͟l͟ y͟a͟w͟n͟s͟ i͟n͟ r͟e͟s͟p͟o͟n͟s͟e͟ t͟o͟ a͟n͟o͟t͟h͟e͟r͟’s͟ y͟a͟w͟n͟. Studies of this behavior in primates have focused on populations in captivity, but biologist Elisabetta Palagi and her colleagues have shown that it can occur in wild primate populations as well. In their study, which focused on a wild population of gelada monkeys (Theropithecus gelada) in Ethiopia, the researchers further reported that yawn contagion most commonly occurred in males and across different social groups instead of within a single social group.',
      question: 'Which choice best describes the function of the first sentence in the text as a whole?',
      choice1: 'It defines a phenomenon that is discussed in the text.',
      choice2: 'It introduces a problem that is examined in the text.',
      choice3: 'It makes a claim that is challenged in the text.',
      choice4: 'It presents a hypothesis that is evaluated in the text.',
      answer: 'A',
      },
      {
      passage: `The following text is adapted from Paul Laurence Dunbar’s 1902 novel The Sport of the Gods. Joe and some of his family members have recently moved to New York City.
    
      [Joe] was wild with enthusiasm and with a desire to be a part of all that the metropolis meant. In the evening he saw the young fellows passing by dressed in their spruce clothes, and he wondered with a sort of envy where they could be going. Back home there had been no place much worth going to, except church and one or two people’s houses.`,
      question: 'Which choice best states the main purpose of the text?',
      choice1: 'It illustrates a character’s reaction to a new environment.',
      choice2: 'It explains why a character has traveled to a city.',
      choice3: 'It compares a character’s thoughts about an event at two different times of day.',
      choice4: 'It presents a character feeling regret over leaving home.',
      answer: 'A',
      },
      {
      passage: `The following text is adapted from Johanna Spyri’s 1881 novel Heidi (translated by Elisabeth Stork in 1915). Eight-year-old Heidi and her friend’s grandmother are looking at some illustrated books.
    
      Heidi had come and was looking with wondering eyes at the splendid pictures in the large books, that Grandmama was showing her. Suddenly she screamed aloud, for there on the picture she saw a peaceful flock grazing on a green pasture. In the middle a shepherd was standing, leaning on his crook. The setting sun was shedding a golden light over everything. With glowing eyes Heidi devoured the scene.`,
      question: 'Which choice best states the main idea of the text?',
      choice1: 'Heidi is upset until she sees a serene image of a pasture in one of Grandmama’s books.',
      choice2: 'Heidi is delighted and fascinated by an image she sees in one of Grandmama’s books.',
      choice3: 'Heidi is initially frightened by an image in one of Grandmama’s books but quickly comes to appreciate its beauty.',
      choice4: 'Heidi is inspecting an image in one of Grandmama’s books because she has never seen a shepherd with his sheep before.',
      answer: 'B',
      },
      {
      passage: 'The painter María Izquierdo played an important role in the development of twentieth-century Mexican art, but her work has never been well-known in the United States except among art historians. One reason for Izquierdo’s relative obscurity is the enormous popularity of some of her peers. In particular, the painters Frida Kahlo and Diego Rivera have so captivated the interest of US audiences that Izquierdo and other Mexican artists from the period often get overlooked, despite the high quality of their work.',
      question: 'Which choice best states the main idea of the text?',
      choice1: 'Izquierdo’s work is not as well-known in the United States as it should be because Kahlo and Rivera draw so much of the public’s attention.',
      choice2: 'During Izquierdo’s lifetime, her paintings were displayed in galleries in the United States much more frequently than paintings by Kahlo and Rivera were.',
      choice3: 'Izquierdo painted some of the same subjects that Kahlo and Rivera painted but used different techniques than they used.',
      choice4: 'Few of Izquierdo’s works are in galleries today because she produced only a small number of paintings.',
      answer: 'A',
      },
      {
      passage: 'The recovery of a 1,000-year-old Chinese shipwreck in the Java Sea near present-day Indonesia has yielded a treasure trove of artifacts, including thousands of small ceramic bowls. Using a portable X-ray fluorescence analyzer tool, Lisa Niziolek and her team were able to detect the chemical composition of these bowls without damaging them. By comparing the chemical signatures of the bowls with those of the materials still at old Chinese kiln sites, Niziolek and her team can pinpoint which Chinese kilns likely produced the ceramic bowls',
      question: 'Which choice best states the main idea of the text?',
      choice1: 'Because of a new technology, researchers can locate and recover more shipwrecks than they could in the past.',
      choice2: 'Researchers have been able to identify the location of a number of Chinese kilns in operation 1,000 years ago.',
      choice3: 'With the help of a special tool, researchers have determined the likely origin of bowls recovered from a shipwreck.',
      choice4: 'Before the invention of portable X-ray fluorescence, researchers needed to take a small piece out of an artifact to analyze its components.',
      answer: 'C',
      },
      {
      passage: 'Sandra Cisneros’s 1984 novella The House on Mango Street made a lasting impact on US literature. Its depiction of Mexican American culture inspired later authors to examine their own heritage within their fictional works. Also influential was the book’s portrayal of the main character, Esperanza, during a pivotal year of her youth. T͟h͟i͟s͟ i͟n͟s͟i͟g͟h͟t͟f͟u͟l͟ d͟e͟p͟i͟c͟t͟i͟o͟n͟ o͟f͟ a͟ p͟r͟e͟t͟e͟e͟n͟ g͟i͟r͟l͟ e͟n͟c͟o͟u͟r͟a͟g͟e͟d͟ a͟u͟t͟h͟o͟r͟s͟ w͟h͟o͟, l͟i͟k͟e͟ C͟i͟s͟n͟e͟r͟o͟s͟ h͟e͟r͟s͟e͟l͟f͟, a͟r͟e͟ L͟a͟t͟i͟n͟a͟ t͟o͟ u͟s͟e͟ f͟i͟c͟t͟i͟o͟n͟a͟l͟ w͟o͟r͟k͟s͟ t͟o͟ e͟x͟a͟m͟i͟n͟e͟ e͟x͟p͟e͟r͟i͟e͟n͟c͟e͟s͟ f͟r͟o͟m͟ t͟h͟e͟i͟r͟ o͟w͟n͟ y͟o͟u͟t͟h͟.',
      question: 'Which statement, if true, would most strongly support the claim in the underlined sentence?',
      choice1: 'In interviews, a number of Latina authors say that The House on Mango Street inspired them to write about their own adolescence in their novels.',
      choice2: 'In published writings, several prominent authors who are not Latina say that reading The House on Mango Street influenced their approach to writing fiction.',
      choice3: 'The House on Mango Street has sold over six million copies and is one of the most commonly read books among high school and university students in the US.',
      choice4: 'Since 1984, new novels about young Latina characters by Latina authors have often been compared to The House on Mango Street.',
      answer: 'A',
      },
      {
        img: 'psat8-9r1-14.png',
      passage: 'A student is researching monthly hours of sunshine in different cities in Alaska. When comparing trends in Anchorage and Fairbanks, the student concludes that the two cities show a similar pattern in the monthly hours of sunshine from April to September.',
      question: 'Which choice best describes data from the graph that support the student’s conclusion?',
      choice1: 'The monthly hours of sunshine in both Anchorage and Fairbanks hold steady in June and July before beginning to decline in August.',
      choice2: 'The monthly hours of sunshine in both Anchorage and Fairbanks increase from April to June and then decrease from June to September.',
      choice3: 'Anchorage and Fairbanks both have less than 200 monthly hours of sunshine from April to September.',
      choice4: 'Anchorage and Fairbanks both have more than 300 monthly hours of sunshine from April to June and less than 200 hours from July to September.',
      answer: 'B',
      },
      {
      img: 'psat8-9r1-15.png',
      passage: 'Swahili is estimated to be the first language of up to 15 million people worldwide. It’s also an officially recognized language in Tanzania, Kenya, and the Democratic Republic of the Congo, which means these countries use Swahili in government documents and proceedings. B͟u͟t͟ e͟v͟e͟n͟ i͟n͟ c͟o͟u͟n͟t͟r͟i͟e͟s͟ w͟h͟e͟r͟e͟ a͟l͟m͟o͟s͟t͟ e͟v͟e͟r͟y͟o͟n͟e͟ s͟p͟e͟a͟k͟s͟ S͟w͟a͟h͟i͟l͟i͟, f͟o͟r͟ m͟a͟n͟y͟ i͟t͟ i͟s͟n͟\'t͟ t͟h͟e͟i͟r͟ f͟i͟r͟s͟t͟ l͟a͟n͟g͟u͟a͟g͟e͟ b͟u͟t͟ i͟s͟ i͟n͟s͟t͟e͟a͟d͟ t͟h͟e͟i͟r͟ s͟e͟c͟o͟n͟d͟, t͟h͟i͟r͟d͟, o͟r͟ e͟v͟e͟n͟ f͟o͟u͟r͟t͟h͟ l͟a͟n͟g͟u͟a͟g͟e͟.',
      question: 'Which choice most effectively uses data from the table to support the underlined claim?',
      choice1: 'Tanzania has approximately 61 million Swahili speakers, which is much more than the estimated total number of people worldwide for whom Swahili is their first language.',
      choice2: 'Tanzania is estimated to have at most 15 million Swahili speakers, while the country’s total population is approximately 61 million people.',
      choice3: 'Approximately 100 percent of the people who speak Swahili as their first language live in Kenya, which has a total population of approximately 55 million people.',
      choice4: 'Approximately 100 percent of Kenya’s population speaks Swahili, while only about 25 percent of the Democratic Republic of the Congo’s population speaks Swahili.',
      answer: 'A',
      },
      {
      passage: 'To create the poems in her 2017 collection One Last Word, poet Nikki Grimes used a writing method called the golden shovel. This method often involves choosing a line from an existing poem and then using each word from that line as the last word of each line in a new poem. Grimes wanted the poems in One Last Word to honor important Black poets of the past, so she chose lines by poets such as Langston Hughes and Georgia Douglas Johnson. Writing in this way can be challenging and might seem as though it would produce awkward poems. However, reviewers praised One Last Word as a beautiful and powerful tribute to the poets who inspired it. This reaction suggests that ______',
      question: 'Which choice most logically completes the text?',
      choice1: 'most reviewers didn’t understand Grimes’s goal for One Last Word.',
      choice2: 'Grimes successfully used the golden shovel method to achieve her goal for One Last Word.',
      choice3: 'Langston Hughes and Georgia Douglas Johnson are two of Grimes’s favorite poets.',
      choice4: 'Grimes inspired many other writers to create poems using the golden shovel method.',
      answer: 'B',
      },
      {
      passage: 'Why are Rome’s famous concrete structures, such as the Colosseum, still standing after 2,000-plus years, when modern concrete may not even last for fifty? Scientists ______ that the secret to Roman concrete’s durability was its unique blend of ingredients, which included volcanic ash and seawater.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      choice1: 'explain',
      choice2: 'having explained',
      choice3: 'explaining',
      choice4: 'to explain',
      answer: 'A',
      },
      {
      passage: 'In the 2011 documentary The Barber of Birmingham, civil rights activist James Armstrong recounts how his barbershop in Birmingham, Alabama, ______ as a political hub for members of the Black community during the 1950s.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      choice1: 'serving',
      choice2: 'having served',
      choice3: 'served',
      choice4: 'to serve',
      answer: 'C',
      },
      {
      passage: 'Led by Syrian American astronomer Shadia Habbal, the Solar Wind Sherpas are an intrepid team of scientists who travel the globe to study solar winds, the streams of particles emanating from the Sun that are only visible from certain locations during a total solar eclipse. When such an eclipse is imminent, the Sherpas pack up their telescopes and ______ ready.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      choice1: 'get',
      choice2: 'had gotten',
      choice3: 'got',
      choice4: 'were getting',
      answer: 'A',
      },
      {
      passage: 'In 2017, artists Isabel and Ruben Toledo redesigned the costumes and sets for The Miami City Ballet’s production of The ______ to reviewers, the Toledos’ designs helped infuse the production with elements of Miami’s Latin American culture.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      choice1: 'Nutcracker according,',
      choice2: 'Nutcracker, according',
      choice3: 'Nutcracker according',
      choice4: 'Nutcracker. According',
      answer: 'D',
      },
      {
      passage: 'Po’Pay was a Tewa leader from Ohkay Owingeh, a pueblo located about twenty-five miles north of present-day Santa Fe, New Mexico. He was instrumental in organizing the Pueblo Revolt of ______ as a result of his leadership, the Spanish colonizers were expelled from the region for a time.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      choice1: '1680',
      choice2: '1680 and',
      choice3: '1680,',
      choice4: '1680, and',
      answer: 'D',
      },
      {
      passage: 'In Gothic architecture, flying buttresses are large arches that help support a building’s exterior walls. Before the Gothic era, cathedrals’ heavy ceilings had to be supported by thick, short walls, but the invention of flying buttresses eliminated this need. ______ Gothic cathedrals could be built with thinner, higher walls.',
      question: 'Which choice completes the text with the most logical transition?',
      choice1: 'Similarly,',
      choice2: 'For instance,',
      choice3: 'Nevertheless,',
      choice4: 'As a result,',
      answer: 'D',
      },
      {
      passage: 'In June, female loggerhead sea turtles will swim back to the sandy beaches where they were born to lay eggs of their own. First, the turtle will dig her nest in the sand. ______ she will lay up to 100 eggs in the nest. Finally, she will cover it all with sand, before returning to the ocean.',
      question: 'Which choice completes the text with the most logical transition?',
      choice1: 'By contrast,',
      choice2: 'Similarly,',
      choice3: 'Next,',
      choice4: 'For example,',
      answer: 'C',
      },
      {
      passage: 'In 1873, Spanish scientist Santiago Ramón y Cajal observed that brain fibers have distinct boundaries with clear end points, a finding that went against earlier assumptions about the brain. ______ scientists had assumed that the brain was a continuous web of fused fibers, not a vast network of distinct, individual cells.',
      question: 'Which choice completes the text with the most logical transition?',
      choice1: 'However,',
      choice2: 'Previously,',
      choice3: 'As a result,',
      choice4: 'Likewise,',
      answer: 'B',
      },
      {
      passage: `While researching a topic, a student has taken the following notes: 
    
      •The Sasanian Empire lasted about 400 years (AD 224 to AD 651).
      •The Sasanians controlled an area spanning 1.4 million square miles.
      •This area included present-day Iran and Iraq.
      •The empire’s capital was the ancient city of Ctesiphon.
      •Ctesiphon was located near present-day Baghdad, Iraq.`,
      question: 'The student wants to specify the location of Ctesiphon. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
      choice1: 'The Sasanian Empire began in AD 224 and ended in AD 651.',
      choice2: 'The capital of the Sasanian Empire, which spanned 1.4 million square miles, was Ctesiphon.',
      choice3: 'The Sasanians controlled an area of 1.4 million square miles, including present-day Iran and Iraq.',
      choice4: 'Ctesiphon, the capital of the Sasanian Empire, was located near present-day Baghdad, Iraq.',
      answer: 'D',
      },
      {
      passage: `While researching a topic, a student has taken the following notes:
    
      •In the art world, the term biennial traditionally refers to an art exhibition that takes place every two years in a single location.
      •Such biennials are held in New York, Berlin, and Venice.
      •In 2006, artists Ed Gomez and Luis Hernandez founded the unconventional MexiCali Biennial.
      •The MexiCali Biennial hosts exhibitions in different venues on both sides of the US-Mexico border.
      •The MexiCali Biennial has taken place on an uneven schedule, with exhibitions in 2006, 2009–10, 2013, and 2018–20.`,
      question: 'The student wants to emphasize a difference between the MexiCali Biennial and traditional biennials. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
      choice1: 'In 2006, artists Ed Gomez and Luis Hernandez founded the MexiCali Biennial, which has taken place in 2006, 2009–10, 2013, and 2018–20.',
      choice2: 'Unlike traditional biennials, the MexiCali Biennial hosts exhibitions in different venues on an uneven schedule.',
      choice3: 'The term biennial traditionally refers to an art exhibition that takes place every two years in a single location, not to exhibitions hosted at a variety of times and venues.',
      choice4: 'Biennial exhibitions have been held in New York, Berlin, and Venice but also on both sides of the US-Mexico border.',
      answer: 'B',
      },
      {
      passage: `While researching a topic, a student has taken the following notes:
    
      •Allan Houser was a Chiricahua Warm Springs Apache sculptor, illustrator, and painter.
      •Many of his sculptures featured Native American figures.
      •He depicted this subject matter using abstract, modernist forms, developing a distinctive style that influenced many other artists.
      •His well-known sculpture Sacred Rain Arrow was pictured on the State of Oklahoma license plate.`,
      question: 'The student wants to describe the distinctive style of Houser’s sculptures. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
      choice1: 'A sculptor, illustrator, and painter, Houser developed a distinctive style for portraying Native American figures.',
      choice2: 'Houser’s sculptures employ abstract, modernist forms to depict Native American figures.',
      choice3: 'Many other artists have been influenced by the style of Houser’s sculptures.',
      choice4: 'The sculpture Sacred Rain Arrow is a well-known example of Houser’s style.',
      answer: 'B',
      }
    ],
    [
      {
      passage: 'Which expression is equivalent to 2 + d² + 2?',
      question: '',
      choice1: 'd² + 24',
      choice2: 'd² + 11',
      choice3: 'd² + 5',
      choice4: 'd² - 11',
      answer: 'B',
      },
      {
      passage: 'The length, y, of a white whale was 162 centimeters (cm) when it was born and increased an average of 4.8 cm per month for the first 12 months after it was born. Which equation best represents this situation, where x is the number of months after the whale was born and y is the length, in cm, of the whale?',
      question: '',
      choice1: 'y = 162x',
      choice2: 'y = 162x + 162',
      choice3: 'y = 4.8x + 4.8',
      choice4: 'y = 4.8x + 162',
      answer: 'D',
      },
      {
      passage: 'If 5x = 20, what is the value of 15x?',
      question: '',
      choice1: '7',
      choice2: '12',
      choice3: '23',
      choice4: '60',
      answer: 'D',
      },
      {
        img: 'psat8_9m1-4.png',
      passage: 'The graph shown models the number of candy bars a certain machine wraps with a label in x seconds.',
      question: 'According to the graph, what is the estimated number of candy bars the machine wraps with a label per second?',
      choice1: '2',
      choice2: '40',
      choice3: '78',
      choice4: '80',
      answer: 'B',
      },
      {
      passage: 'The area of a square is 64 square inches. What is the side length, in inches, of this square?',
      question: '',
      choice1: '8',
      choice2: '16',
      choice3: '64',
      choice4: '128',
      answer: 'A',
      },
      {
      passage: 'Connor has c dollars and Maria has m dollars. Connor has 4 times as many dollars as Maria, and together they have a total of $25.00. Which system equations represents this situation?',
      question: '',
      choice1: 'c = 4m // c + m = 25',
      choice2: 'm = 4c // c + m = 25',
      choice3: 'c = 25m // c + m = 4',
      choice4: 'm = 25c // c + m = 4',
      answer: 'A',
      },
      {
      passage: 'd = 16t',
      question: 'The given equation represents the distance d, in inches, where t represents the number of seconds since an object started moving. Which of the following is the best interpretation of 16 in this context?',
      choice1: 'The object moved a total of 16 inches.',
      choice2: 'The object moved a total of 16t inches.',
      choice3: 'The object is moving at a rate of 16 inches per second.',
      choice4: 'The object is moving at a rate of 1/16 inches per second.',
      answer: 'C',
      },
      {
      passage: 'The equation 46 = 2a + 2b gives the relationship between the side lengths a and b of a certain parallelogram. If a = 9, what is the value of b?',
      question: '',
      fr: true,
      answer: 14,
      },
      {
      passage: '4, 9, 14, 23, 32',
      question: 'What is the mean of the data shown?',
      choice1: '14',
      choice2: '16',
      choice3: '17',
      choice4: '32',
      answer: 'B',
      },
      {
      passage: `y = 4x - 9
  y = 19`,
      question: 'What is the solution (x, y) to the given system of equations?',
      choice1: '(4, 19)',
      choice2: '(7, 19)',
      choice3: '(19, 4)',
      choice4: '(19, 7)',
      answer: 'B',
      },
      {
      passage: 'Which expression is equivalent to 256w² - 676?',
      question: '',
      choice1: '(16w - 26)(16w - 26)',
      choice2: '(8w - 13)(8w + 13)',
      choice3: '(8w - 13)(8w - 13)',
      choice4: '(16w - 26)(16w + 26)',
      answer: 'D',
      },
      {
        img: 'psat8_9m1-12.png',
      passage: 'Scientists recorded data about the ocean water levels at a certain location over a period of 6 hours. The graph shown models the data, where y = 0 represents sea level. Which table gives values of x and their corresponding values of y based on the model?',
      question: '',
      choice1img: 'psat8_9m1-12-1.png',
      choice2img: 'psat8_9m1-12-2.png',
      choice3img: 'psat8_9m1-12-3.png',
      choice4img: 'psat8_9m1-12-4.png',
      answer: 'C',
      },
      {
      passage: 'The function f is defined by f(x) = 6 + √x. What is the value of f(36)?',
      question: '',
      fr: true,
      answer: 12,
      },
      {
      passage: 'The function f(x) = 200,000(1.21)ˣ gives a company\'s predicted annual revenue, in dollars, x years after the company started selling light bulbs online, where 0 < x ≤ 10. What is the best interpretation of the statement "f(5) is approximately equal to 518,748" in this context?',
      question: '',
      choice1: '5 years after the company started selling light bulbs online, its predicted annual revenue is approximately 518,748 dollars.',
      choice2: '5 years after the company started selling light bulbs online, its predicted annual revenue will have increased by a total of approximately 518,748 dollars.',
      choice3: 'When the company’s predicted annual revenue is approximately 518,748 dollars, it is 5 times the predicted annual revenue for the previous year.',
      choice4: 'When the company’s predicted annual revenue is approximately 518,748 dollars, it is 5% greater than the predicted annual revenue for the previous year.',
      answer: 'A',
      },
      {
      img: 'psat8_9m1-15.png',
      passage: 'In the given scatterplot, a line of best fit for the data is shown.',
      question: 'Which of the following is closest to the slope of this line of best fit?',
      choice1: '7',
      choice2: '0.7',
      choice3: '-0.7',
      choice4: '-7',
      answer: 'C',
      },
      {
      passage: 'q - 29r = s',
      question: 'The given equation relates the positive numbers q, r, and s. Which equation correctly expresses q in terms of r and s?',
      choice1: 'q = s - 29r',
      choice2: 'q = s + 29r',
      choice3: 'q = 29rs',
      choice4: 'q = -s/29r',
      answer: 'B',
      },
      {
      passage: 'A distance of 112 furlongs is equivalent to how many feet? (1 furlong = 220 yards and 1 yard = 3 feet)',
      question: '',
      fr: true,
      answer: 73920,
      },
      {
      passage: 'A right triangle with lengths of 28 centimeters and 20 centimeters. What is the length of this triangle\'s hypotenuse, in centimeters?',
      question: '',
      choice1: '8√6',
      choice2: '4√74',
      choice3: '48',
      choice4: '1,184',
      answer: 'B',
      },
      {
      passage: 'j(x) = mx + 114',
      question: 'For the linear function j, m is a constant and j(12) = 18. What is the value of j(10)?',
      fr: true,
      answer: 39,
      },
      {
      passage: 'x² - 40x - 10 = 0',
      question: 'What is the sum of the solutions to the given equation?',
      choice1: '0',
      choice2: '5',
      choice3: '10',
      choice4: '40',
      answer: 'D',
      },
      {
      passage: 'If 3x² - 18x - 15 = 0, what is the value of x² - 6x?',
      question: '',
      fr: true,
      answer: 5,
      },
      {
      passage: 'The value of a collectible comic book increased by 167% from the end of 2011 to the end of 2012 and then decreased by 16% from the end of 2012 to the end of 2013. What was the net percentage increase in the value of the collectible comic book from the end of 2011 to the end of 2013?',
      question: '',
      choice1: '124.28%',
      choice2: '140.28%',
      choice3: '151.00%',
      choice4: '209.72%',
      answer: 'A',
      }
    ],
    [
      {
      passage: 'Which expression is equivalent to 8 + d² + 3?',
      question: '',
      choice1: 'd² + 24',
      choice2: 'd² + 11',
      choice3: 'd² + 5',
      choice4: 'd² - 11',
      answer: 'B',
      },
      {
      passage: 'The length, y, of a white whale was 162 centimeters (cm) when it was born and increased an average of 4.8 cm per month for the first 12 months after it was born. Which equation best represents this situation, where x is the number of months after the whale was born and y is the length, in cm, of the whale?',
      question: '',
      choice1: 'y = 162x',
      choice2: 'y = 162x + 162',
      choice3: 'y = 4.8x + 4.8',
      choice4: 'y = 4.8x + 162',
      answer: 'D',
      },
      {
      passage: 'If 5x = 20, what is the value of 15x?',
      question: '',
      choice1: '7',
      choice2: '12',
      choice3: '23',
      choice4: '60',
      answer: 'D',
      },
      {
        img: 'psat8_9m1-4.png',
      passage: 'The graph shown models the number of candy bars a certain machine wraps with a label in x seconds.',
      question: 'According to the graph, what is the estimated number of candy bars the machine wraps with a label per second?',
      choice1: '2',
      choice2: '40',
      choice3: '78',
      choice4: '80',
      answer: 'B',
      },
      {
      passage: 'The area of a square is 64 square inches. What is the side length, in inches, of this square?',
      question: '',
      choice1: '8',
      choice2: '16',
      choice3: '64',
      choice4: '128',
      answer: 'A',
      },
      {
      passage: 'Connor has c dollars and Maria has m dollars. Connor has 4 times as many dollars as Maria, and together they have a total of $25.00. Which system equations represents this situation?',
      question: '',
      choice1: 'c = 4m // c + m = 25',
      choice2: 'm = 4c // c + m = 25',
      choice3: 'c = 25m // c + m = 4',
      choice4: 'm = 25c // c + m = 4',
      answer: 'A',
      },
      {
      passage: 'd = 16t',
      question: 'The given equation represents the distance d, in inches, where t represents the number of seconds since an object started moving. Which of the following is the best interpretation of 16 in this context?',
      choice1: 'The object moved a total of 16 inches.',
      choice2: 'The object moved a total of 16t inches.',
      choice3: 'The object is moving at a rate of 16 inches per second.',
      choice4: 'The object is moving at a rate of 1/16 inches per second.',
      answer: 'C',
      },
      {
      passage: 'The equation 46 = 2a + 2b gives the relationship between the side lengths a and b of a certain parallelogram. If a = 9, what is the value of b?',
      question: '',
      fr: true,
      answer: 14,
      },
      {
      passage: '4, 9, 14, 23, 32',
      question: 'What is the mean of the data shown?',
      choice1: '14',
      choice2: '16',
      choice3: '17',
      choice4: '32',
      answer: 'B',
      },
      {
      passage: `y = 4x - 9
  y = 19`,
      question: 'What is the solution (x, y) to the given system of equations?',
      choice1: '(4, 19)',
      choice2: '(7, 19)',
      choice3: '(19, 4)',
      choice4: '(19, 7)',
      answer: 'B',
      },
      {
      passage: 'Which expression is equivalent to 256w² - 676?',
      question: '',
      choice1: '(16w - 26)(16w - 26)',
      choice2: '(8w - 13)(8w + 13)',
      choice3: '(8w - 13)(8w - 13)',
      choice4: '(16w - 26)(16w + 26)',
      answer: 'D',
      },
      {
        img: 'psat8_9m1-12.png',
      passage: 'Scientists recorded data about the ocean water levels at a certain location over a period of 6 hours. The graph shown models the data, where y = 0 represents sea level. Which table gives values of x and their corresponding values of y based on the model?',
      question: '',
      choice1img: 'psat8_9m1-12-1.png',
      choice2img: 'psat8_9m1-12-2.png',
      choice3img: 'psat8_9m1-12-3.png',
      choice4img: 'psat8_9m1-12-4.png',
      answer: 'C',
      },
      {
      passage: 'The function f is defined by f(x) = 6 + √x. What is the value of f(36)?',
      question: '',
      fr: true,
      answer: 12,
      },
      {
      passage: 'The function f(x) = 200,000(1.21)ˣ gives a company\'s predicted annual revenue, in dollars, x years after the company started selling light bulbs online, where 0 < x ≤ 10. What is the best interpretation of the statement "f(5) is approximately equal to 518,748" in this context?',
      question: '',
      choice1: '5 years after the company started selling light bulbs online, its predicted annual revenue is approximately 518,748 dollars.',
      choice2: '5 years after the company started selling light bulbs online, its predicted annual revenue will have increased by a total of approximately 518,748 dollars.',
      choice3: 'When the company’s predicted annual revenue is approximately 518,748 dollars, it is 5 times the predicted annual revenue for the previous year.',
      choice4: 'When the company’s predicted annual revenue is approximately 518,748 dollars, it is 5% greater than the predicted annual revenue for the previous year.',
      answer: 'A',
      },
      {
      img: 'psat8_9m1-15.png',
      passage: 'In the given scatterplot, a line of best fit for the data is shown.',
      question: 'Which of the following is closest to the slope of this line of best fit?',
      choice1: '7',
      choice2: '0.7',
      choice3: '-0.7',
      choice4: '-7',
      answer: 'C',
      },
      {
      passage: 'q - 29r = s',
      question: 'The given equation relates the positive numbers q, r, and s. Which equation correctly expresses q in terms of r and s?',
      choice1: 'q = s - 29r',
      choice2: 'q = s + 29r',
      choice3: 'q = 29rs',
      choice4: 'q = -s/29r',
      answer: 'B',
      },
      {
      passage: 'A distance of 112 furlongs is equivalent to how many feet? (1 furlong = 220 yards and 1 yard = 3 feet)',
      question: '',
      fr: true,
      answer: 73920,
      },
      {
      passage: 'A right triangle with lengths of 28 centimeters and 20 centimeters. What is the length of this triangle\'s hypotenuse, in centimeters?',
      question: '',
      choice1: '8√6',
      choice2: '4√74',
      choice3: '48',
      choice4: '1,184',
      answer: 'B',
      },
      {
      passage: 'j(x) = mx + 114',
      question: 'For the linear function j, m is a constant and j(12) = 18. What is the value of j(10)?',
      fr: true,
      answer: 39,
      },
      {
      passage: 'x² - 40x - 10 = 0',
      question: 'What is the sum of the solutions to the given equation?',
      choice1: '0',
      choice2: '5',
      choice3: '10',
      choice4: '40',
      answer: 'D',
      },
      {
      passage: 'If 3x² - 18x - 15 = 0, what is the value of x² - 6x?',
      question: '',
      fr: true,
      answer: 5,
      },
      {
      passage: 'The value of a collectible comic book increased by 167% from the end of 2011 to the end of 2012 and then decreased by 16% from the end of 2012 to the end of 2013. What was the net percentage increase in the value of the collectible comic book from the end of 2011 to the end of 2013?',
      question: '',
      choice1: '124.28%',
      choice2: '140.28%',
      choice3: '151.00%',
      choice4: '209.72%',
      answer: 'A',
      }
    ]
]

export const sampletopics = [
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Words in Context',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Text Structure and Purpose',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Cross-Text Connections',
    'Linear equation word problems',
    'Graphs of linear equations and functions',
    'Operations with polynomials',
    'Linear relationship word problems',
    'Linear relationship word problems',
    'Solving linear equations and inequalities',
    'Isolating quantities',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
    'Linear equation word problems',
    'Graphs of linear equations and functions',
    'Operations with polynomials',
    'Linear relationship word problems',
    'Linear relationship word problems',
    'Solving linear equations and inequalities',
    'Isolating quantities',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
    'Linear equation word problems',
    'Graphs of linear equations and functions',
    'Operations with polynomials',
    'Linear relationship word problems',
    'Linear relationship word problems',
    'Solving linear equations and inequalities',
    'Isolating quantities',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
    'Linear equation word problems',
    'Graphs of linear equations and functions',
    'Operations with polynomials',
    'Linear relationship word problems',
    'Linear relationship word problems',
    'Solving linear equations and inequalities',
    'Isolating quantities',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
    'Operations with polynomials',
    'Quadratic and exponential word problems',
]

export const diff = [
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Easy',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Medium',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard',
  'Hard'
]